[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
revenue_engine = "E2KG7u7hZnRPVF56hc3hpqMKnBiBUWVgwbqpHJNQWmNV"
mock_swap_program = "7GM2yrPoFCBta5j5KxzqLU2xPAs2sEZbrYD4HnNVvLBp"
staking_program = "EWmrkAfChNnuhCm5nbfwZMwuhn3PN8nF4bfTX9GuyDdQ"

[programs.devnet]
revenue_engine = "E2KG7u7hZnRPVF56hc3hpqMKnBiBUWVgwbqpHJNQWmNV"
mock_swap_program = "7GM2yrPoFCBta5j5KxzqLU2xPAs2sEZbrYD4HnNVvLBp"
staking_program = "EWmrkAfChNnuhCm5nbfwZMwuhn3PN8nF4bfTX9GuyDdQ"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json --timeout 1000000 'tests/**/*.ts'"