[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
revenue_engine = "DNEYpF5jMNjpxAPNYQhPkpuaxWGudBTvyrmKDkNQdZMP"
mock_swap_program = "G9gP6qjaZcAyKaCzszcvABkd5UUorfnFe9PjnRkm7qKS"
staking_program = "DNEYpF5jMNjpxAPNYQhPkpuaxWGudBTvyrmKDkNQdZMP"

[programs.devnet]
revenue_engine = "9NJ5YRHFmX8CCbsjfueBVxnFTgi2FGrkEu2yjMyTHpoB"
mock_swap_program = "2DFGw43xgCpr5mJoBPGphdZPBWjDpiaHPRWPGfenxJ2y"
staking_program = "GkvVXqtEkmEUJdnrXxA7KBdjC7rGtP1mrCFGpdCMoT8i"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keypairs/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json --timeout 1000000 'tests/**/*.ts'"