import React, { useEffect, useRef } from 'react';
import '../../App.css';

interface LogViewerProps {
    logs: string[]; // HTML string array
}

const LogViewer = ({ logs }: LogViewerProps) => {
    const logContainerRef = useRef<HTMLDivElement>(null);

    // Scroll to top when new logs are added
    useEffect(() => {
        if (logContainerRef.current) {
            logContainerRef.current.scrollTop = 0;
        }
    }, [logs]);

    return (
        <div className="log-container" ref={logContainerRef}>
            {logs.length === 0 ? (
                <p>No logs yet...</p>
            ) : (
                logs.map((log, index) => (
                    // dangerouslySetInnerHTML is for rendering HTML generated by log formatting function
                    <div key={index} dangerouslySetInnerHTML={{ __html: log }}></div>
                ))
            )}
        </div>
    );
};

export default LogViewer;